@baseUrl = http://localhost:3000/api/v1
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODRhZTFhNi1lMTJhLTQ4Y2UtOWVhZC1lOTY1ZDU2ZTEzNDkiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzgxOTAyNDU5LCJleHAiOjE3ODE5MDMzNTl9.GT3vpZxA69So9U0aFxl6f_dkB97GZaKkunL37-Uh2nY

### Auth: register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "password": "contrasena123"
}

###
// Auth: register admin user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "lastName": "User",
  "email": "admin@example.com",
  "password": "Admin123",
  "Role": "ADMIN"
}


###
// Auth: login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin123"
}

###
// Auth: logout
POST {{baseUrl}}/auth/logout
Authorization: {{accessToken}}

###
// Users: current profile
GET {{baseUrl}}/users/profile
Authorization: {{accessToken}}

###
// Users: update current profile
PATCH {{baseUrl}}/users/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "name": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com"
}

###
// Users: change password
PATCH {{baseUrl}}/users/profile/password
Authorization: {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "contrasena123",
  "newPassword": "NewPass123"
}

###
// Users: delete current account
DELETE {{baseUrl}}/users/profile
Authorization: {{accessToken}}

###
// Admin only: list all users
GET {{baseUrl}}/users
Authorization: {{accessToken}}

###
// Admin only: get user by id
GET {{baseUrl}}/users/1fb33121-08a0-4fba-90d7-4c43a7e392b7
Authorization: {{accessToken}}

###
// Admin only: delete user by id
DELETE {{baseUrl}}/users/1fb33121-08a0-4fba-90d7-4c43a7e392b7
Authorization: {{accessToken}}
