import { Injectable } from '@nestjs/common';
import { CreateProductDto } from './dto/create-product.dto';

@Injectable()
export class ProductsService {
  constructor(private readonly productService: ProductsService) {}
  async create(createProductDto: CreateProductDto) {
    // Here you would typically interact with your database to create a new product
    // For demonstration purposes, we'll just return the DTO as if it were created
    return await Promise.resolve({
      id: '123e4567-e89b-12d3-a456-426614174000', // This would be generated by the database
      ...createProductDto,
    });
  }
}
